### ISSUE TITLE
@db is changed to @[object Object]

### ISSUE THREAD

**Issue by chemicalkosek** [prisma/upgrade#100]
During the last step of the prisma upgrade CLI the `@db` is changed to `@[object Object]`

In example the following:
```
@db.VarChar(30)
```
is changed to:
```
@[object Object].VarChar(30)
```

**Comment by omar-dulaimi** [comment]
I can confirm this happened as well in our project.

**Comment by smschick** [comment]
Also happening for me

**Comment by matthewmueller** [comment]
Hey, sorry about that. I'll be looking into this soon.

**Comment by matthewmueller** [comment]
Hey, this is fixed in `0.0.43`
