### ISSUE TITLE
Do not read `url` from P2 schema (to not fail if it is an env var)

### ISSUE THREAD

**Issue by janpio** [prisma/upgrade#12]
Not needed in the tool afaik.

**Comment by matthewmueller** [comment]
woops, this is a regression from adding postgres. should be able to remove by looking at prisma.yml

https://prisma-company.slack.com/archives/C010EAVUX0D/p1590747787007600

**Comment by matthewmueller** [comment]
fixed in tmp-prisma-upgrade@0.0.12
