### ISSUE TITLE
cli doesn't recognize mysql url

### ISSUE THREAD

**Issue by RLuckom** [prisma/upgrade#123]
I ran the cli and got the error `We could not determine your endpoint. It's probably in an environment variable`

My database is mysql; the url is structurally identical to `'mysql://root:pass@localhost:3306/default@default`

In the [cli index](https://github.com/prisma/upgrade/blob/main/src/cli/index.ts#L155) it appears that `prisma-upgrade` is using the `is-url` package to test the supplied urls.

When I use `is-url` to test my db connection string, it returns `false`

```
isUrl = require('is-url')
console.log(isUrl('mysql://root:pass@localhost:3306/default@default'))
 ```
 
 I apologize if I've misunderstood something but for now I am stuck.

**Comment by janpio** [comment]
Which instructions are you following where it tells you to use the CLI with that parameter? Can you link to the guide in our docs?

My current guess: This might be asking for your Prisma 1 endpoint, and not a database connection string.

**Comment by RLuckom** [comment]
Thanks! I think I understand. I was following these instructions: https://www.prisma.io/docs/guides/upgrade-guides/upgrade-from-prisma-1/upgrading-the-prisma-layer-postgres#5-use-the-prisma-schema-upgrade-cli-to-resolve-schema-incompatibilities . The earlier half of those instructions is talking about the mysql connection string, which can be either in your prisma schema or in an environment variable. Mine is in an environment variable. Then I ran the prisma command as specified in the link, and the full error reads:

```
Error We could not determine your endpoint. It's probably in an environment variable.

Please use the --url flag to specify the endpoint.

Run `prisma-upgrade -h` for more details.

Note: The url is not used to connect to your database, only to determine the schema name.
```

and it seemed like that meant the db url. I'll try with the prisma url and report back. Thank you!

**Comment by janpio** [comment]
Yep, we should have called that `--endpoint` instead I would say, then it would be harder to confuse.

**Comment by RLuckom** [comment]
So as the error says, you get the schema name from the endpoint string of the prisma instance?

**Comment by RLuckom** [comment]
It worked with the prisma endpoint so I closed this issue. Thank you for helping me!

**Comment by janpio** [comment]
Of course, and sorry for the confusion.
