### ISSUE TITLE
Using `@prisma/upgrade` with Prisma 1 MongoDB schema should show error message (and link)

### ISSUE THREAD

**Issue by janpio** [prisma/upgrade#129]
As the upgrade path probably does not involve this tool (but be done via https://github.com/prisma/docs/issues/2767), we should prevent users from using it with such schemas.

**Comment by Jolg42** [comment]
Can probably be done here
https://github.com/prisma/upgrade/blob/main/src/api/index.ts#L27-L28

**Comment by Jolg42** [comment]
PR open https://github.com/prisma/upgrade/pull/130
I need an error message and a code review 
<img width="795" alt="Screen Shot 2022-02-18 at 11 16 20" src="https://user-images.githubusercontent.com/1328733/154664295-c6584d78-d7e4-456e-8977-4ce6833be4cc.png">

**Comment by Jolg42** [comment]
Note: @matthewmueller will merge and publish once the docs are finished.

**Comment by matthewmueller** [comment]
Depends on #https://github.com/prisma/docs/issues/2767
