### ISSUE TITLE
Allow user to skip individual SQL commands that can not be executed or they choose not to run

### ISSUE THREAD

**Issue by janpio** [prisma/upgrade#13]
Otherwise some wrong things will make it unable to finish the process

**Comment by matthewmueller** [comment]
hmmm... I see the point, but what are some of these things? Are those bugs that we should fix?

Probably makes sense to offer a `--write` flag that will write to the P2 schema regardless.

**Comment by janpio** [comment]
E.g. defaults on mediumtext, which can not have defaults in MySQL.

But a user also might just decide to skip some of the queries because they are not comfortable with running them.

I think the real solution here is more https://prisma-company.slack.com/archives/C010EAVUX0D/p1590739253006300

**Comment by matthewmueller** [comment]
My interpretation of the suggested workflow doesn't solve this issue. Please play with 0.0.9 and let me know if I've misinterpreted the workflow.

**Comment by janpio** [comment]
> If not, explain that to the user and still give them an option to proceed.

would be the escape hatch here.

**Comment by matthewmueller** [comment]
Ah. I see. Currently, it's the welcome screen all over again. I'll have to see if there's a way to *know* they've already run the prisma-upgrade tool once already.

**Comment by janpio** [comment]
I think you can avoid having to add a local storage here - just show it on the first run as well. "If you made all the SQL changes you are comfortable with, press `y` to proceed to the next step with outstanding SQL changes" or something like that could work.

**Comment by matthewmueller** [comment]
This is fixed in `0.0.11`
