### ISSUE TITLE
PostgreSQL statements don't include schema and lack quotes for tables

### ISSUE THREAD

**Issue by nikolasburk** [prisma/upgrade#14]
It seems like the SQL statements generated for Postgres lack some information to be runnable just from copy/pasting.

For example, I currently get the following generated statements to set `DEFAULT` values:

```
Let's transition Prisma 1's @default's to default values backed by the database. Run the following SQL command against your database:
      
  ALTER TABLE User ALTER COLUMN role SET DEFAULT 'CUSTOMER';
  ALTER TABLE Post ALTER COLUMN published SET DEFAULT FALSE;
``` 

However, this statement doesn't work e.g. when using a client like Postico for two reasons:

- It lacks the _schema_ namespace for the `User` and `Post` tables
- It lacks quotes around the table names that tell Postgres to not ignore the casing

Assuming my schema is called `default$default`, then the same SQL statements need to looks as follows:

```sql
ALTER TABLE default$default."User" ALTER COLUMN role SET DEFAULT 'CUSTOMER';
ALTER TABLE default$default."Post" ALTER COLUMN published SET DEFAULT FALSE;
```

To be safe, we could also add quotes around the schema names because some users might have uppercase letters in there too:

```sql
ALTER TABLE "default$default"."User" ALTER COLUMN role SET DEFAULT 'CUSTOMER';
ALTER TABLE "default$default"."Post" ALTER COLUMN published SET DEFAULT FALSE;
```

**Comment by nikolasburk** [comment]
Same for column names:

```
ALTER TABLE Post ALTER COLUMN createdAt SET DEFAULT CURRENT_TIMESTAMP;
```

should be:

```
ALTER TABLE "default$default"."Post" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
````

**Comment by matthewmueller** [comment]
should be fixed in `tmp-prisma-upgrade`

**Comment by nikolasburk** [comment]
Indeed ❤️
