### ISSUE TITLE
CLI suggests default `CURRENT_TIMESTAMP` for `@updatedAt`

### ISSUE THREAD

**Issue by nikolasburk** [prisma/upgrade#2]
The tool suggests to add the `DEFAULT` value `CURRENT_TIMESTAMP` for a field that was annotated with `@updatedAt` in the DB:

```
Let's transition Prisma 1's @updatedAt to a datetime type with a default value of now. Run the following SQL command against your database:
      
  ALTER TABLE Post CHANGE updatedAt updatedAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP;

? Done migrating @updatedAt? Press 'y' to continue › (y/N)
```

While this might yield the right behaviour for the initial creation of records, it doesn't actually provide the right behaviour because it won't update when the record is updated any more (if I understand correctly).

I believe the only workaround to get the same behaviour is to add the `@updatedAt` attribute in the new Prisma schema as documented here: https://www.prisma.io/docs/guides/upgrade-from-prisma-1/schema-incompatibilities/#updatedat-isnt-represented-in-database

Should we remove that behaviour for `@updatedAt` or do we feel this is "better than nothing"?

**Comment by janpio** [comment]
The wanted behavior is currently not clearly defined on https://www.notion.so/prismaio/Limitations-of-Introspection-of-Prisma-1-schemas-Workarounds-24cfc8cb8cc3402281ee708f66339d42#0714fc5267ed456b8e5a93efaa748d45. The link beneath that headline (https://www.notion.so/prismaio/Updated-At-Details-2b0131e74feb4ff9b386b07165ed5888) suggests something similar but slightly different.

**Comment by nikolasburk** [comment]
If I understand correctly, this statement would work:

```sql
ALTER TABLE User MODIFY COLUMN updatedAt datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
```

However, it seems that this only works for MySQL? Does Postgres support something similar as well? If now, how do we want to handle these differences?

**Comment by nikolasburk** [comment]
Any updates on this one @janpio @divyenduz?

**Comment by matthewmueller** [comment]
So this is exactly the kind of work I need to do to make Postgres work with the upgrade tool. 

I already know how to do this in Postgres, something like:

```
ALTER TABLE User set column updatedAt datetime NOT NULL DEFAULT;
```

I don't think I need help on determining these, I could have used the help to figure this out for MySQL because I had to learn these SQL adjustments, but for Postgres, I know already.

**Comment by matthewmueller** [comment]
This is currently blocked by introspection not being able to pickup @updatedAt: https://prisma-company.slack.com/archives/CGLQ50TK2/p1590766795246600

Right now we add an @updatedAt to the P2 schema automatically after all SQL changes have been applied, but it would certainly be better if introspection picked this up.

**Comment by nikolasburk** [comment]
Thanks for clarifying @matthewmueller 🙏 in that case, should we entire skip the SQL statements for `@updatedAt` in the CLI since it currently doesn't yield the right results (because it suggests to use `CURRENT_TIMESTAMP` which is not the expected behavior for `@updatedAt`)?

**Comment by matthewmueller** [comment]
That's a possibility. From my perspective @updatedAt should do 2 things:

1. Set the field to the current timestamp when the record is created
2. Update the field to a new timestamp whenever the record is updated

I don't see why we shouldn't do 1) inside the database in the same way that we do it with `default(now())`

At the same time, it does allow me to remove a (trivial) amount of code, where I can remove these SQL commands and I can remove the logic to replace `@default(now())` with `@updateAt` after introspection.

I guess it depends if prisma migrate will do this. I could see us getting into trouble if we choose one way today, and then do it a different way in the future.

**Comment by nikolasburk** [comment]
So, here's my suggestion:

## Preferred solution

If we're confident about the required SQL that needs to be put in place to replicate the `@updatedAt` behaviour (which [it seems we are](https://github.com/prisma/prisma/issues/2650#issue-629902402)), I'd prefer spitting out these SQL statements regardless of whether introspection is currently able to pick it up. 

As long as the behavior manifests in the DB, "it's there" and that's what counts for the user (regardless of whether it manifests in the Prisma schema or not).

## Second-preferred solution

Skip the SQL statements altogether and add `@updatedAt` when `prisma-upgrade` is invoked the second time.

Right now, `@updatedAt` is only a Prisma-level feature, similar e.g. to `@default(cuid())` so it never manifests in the DB. In that sense, I think we can follow a similar approach as with `@default(cuid())` and add it during the second run of `prisma-upgrade`.

## Notes

I'm against replacing `@updatedAt` with `@default(now())` as we do right now. Mostly because this doesn't give users the right behaviour while we do have two potential solutions (see above) to actually give them the correct behaviour.

**Comment by nikolasburk** [comment]
> Going with the 2nd preferred solution is probably safer, but might mean there's another upgrade in the future.

I think this is a general problem for _everyone_ who uses `@updatedAt` (not only Prisma 1 users who upgrade) right now so I'd not see this as a major issue in this case (since we'll need a strategy for dealing with this anyways at some point).

**Comment by matthewmueller** [comment]
Done in 0.0.12
