### ISSUE TITLE
DEFAULTs for enums are missing in generated SQL statements

### ISSUE THREAD

**Issue by nikolasburk** [prisma/upgrade#23]
In my Prisma 1 datamodel, I have a default value for an enum:

```graphql
type User {
  id: ID! @id
  email: String @unique
  name: String!
  role: Role! @default(value: CUSTOMER)
  jsonData: Json 
  profile: Profile
  posts: [Post!]!
}

enum Role {
  ADMIN
  CUSTOMER
}
```

Right now, the generated SQL only includes instructions for the conversion into an enum:

```
  Turn the columns string type into a enum type for Enum fields
  https://pris.ly/d/schema-incompatibilities#enums-are-represented-as-text-in-database

    CREATE TYPE "demo1$dev"."Role" AS ENUM ('ADMIN', 'CUSTOMER');
ALTER TABLE "demo1$dev"."User" ALTER COLUMN "role" SET DATA TYPE "demo1$dev"."Role" using "role"::"demo1$dev"."Role";
```

But it's missing the setting of the default value:

```
  Add missing `DEFAULT` constraints to the database
  https://pris.ly/d/schema-incompatibilities#default-values-arent-represented-in-database

    ALTER TABLE "demo1$dev"."Post" ALTER COLUMN "published" SET DEFAULT false;
```

I guess this is a bit more of a tricky case because the DEFAULT value can only be set _after_ the column was converted to an enum, so this basically introduces a "dependency" between the SQL statements requiring that some after executed before others...

**Comment by matthewmueller** [comment]
Good catch! I'll see if I can fix this.

**Comment by matthewmueller** [comment]
Fixed by: https://github.com/prisma/upgrade/commit/68239ff4eb7197fc4b1f9b8c695e4c644b9588bf

Caveat in: https://github.com/prisma/upgrade/commit/c819cfd7d25f43834402d5bd527409b297d1bf03
