### ISSUE TITLE
Maintain order of models and fields from Prisma 1 datamodel

### ISSUE THREAD

**Issue by nikolasburk** [prisma/upgrade#24]
The Upgrade CLI currently writes the final Prisma schema by ordering model and field names alphabetically. 

Ideally, the model and field names can use the same ordering as in the Prisma 1 so that the new Prisma 2 schema looks _familiar_ to the folks who are upgrading.

**Comment by matthewmueller** [comment]
It appears that [re-introspection will address this](https://github.com/prisma/prisma-engines/pull/872).

**Comment by janpio** [comment]
Introspection will actually support that, Re-Introspection is not involved here.

The upgrade tool does not order any models and fields itself?

**Comment by matthewmueller** [comment]
Nope

**Comment by janpio** [comment]
Nice, let's hope we get this into 2.3 then.
