### ISSUE TITLE
[Feature] Fix scalar lists that were represented with extra table

### ISSUE THREAD

**Issue by nikolasburk** [prisma/upgrade#28]
The exact problem + SQL workaround are described here: https://www.prisma.io/docs/guides/upgrade-from-prisma-1/schema-incompatibilities-postgres#scalar-lists-arrays-are-maintained-with-extra-table

Note that this requires a data migration, so we should figure out a good way how to integrate it in the Upgrade CLI (e.g. as an additional step after all the SQL that only perform Prisma-1-compatible changes was printed).

Internal link: https://www.notion.so/prismaio/Limitations-of-Introspection-of-Prisma-1-schemas-Workarounds-24cfc8cb8cc3402281ee708f66339d42#c97d46a729834358b08dde98357bf8ff

**Comment by Aldrian** [comment]
Would it be possible to integrate the PostgreSQL workaround into prisma upgrade as an extra step, if schema.prisma has a postgresql provider declared in the datasource?

**Comment by matthewmueller** [comment]
FYI: I'll be working on this very soon.

**Comment by matthewmueller** [comment]
**Note:** This will only work for Postgres since [P2 doesn't support scalar lists on MySQL and SQLite](https://www.prisma.io/docs/reference/tools-and-interfaces/prisma-schema/models#lists)

**Comment by matthewmueller** [comment]
**WIP**

The SQL is going to look something like this:

```sql
ALTER TABLE "postgres-scalar-lists$dev"."User" ADD COLUMN "coinflips" boolean[] NOT NULL;

-- doesn't work yet
update
  "postgres-scalar-lists$dev"."User" as u
set
  coinflips = array(c.value)
from
  (select * from "postgres-scalar-lists$dev"."User_coinflips" order by position) as c
where
  c.nodeId = u.id;

ALTER TABLE "postgres-scalar-lists$dev"."User" SET COLUMN "coinflips" NOT NULL;

DROP "postgres-scalar-lists$dev"."User_coinflips";
```

**Comment by matthewmueller** [comment]
Okay this should be fixed by #57. Please give it a try in `0.0.33`.

**Comment by Aldrian** [comment]
I'm getting `ERROR: ERROR:  column "interestedFeatures" contains null values` errors

SQL statements: 
```sql
ALTER TABLE "default$default"."User" ADD COLUMN "interestedFeatures" text[];
UPDATE "default$default"."User" u
SET "interestedFeatures" = t."value"::text[]
FROM (
    SELECT "nodeId", array_agg(value ORDER BY position) as value
    FROM "default$default"."User_interestedFeatures"
    GROUP BY "nodeId"
) t
WHERE t."nodeId" = u."id";
ALTER TABLE "default$default"."User" ALTER COLUMN "interestedFeatures" SET NOT NULL;
DROP TABLE "default$default"."User_interestedFeatures";
```

When I ran those migrations manually, my statements were: 

```sql
ALTER TABLE "default$default"."User" ADD COLUMN interestedFeatures text[];
UPDATE "default$default"."User"
  SET interestedFeatures = t.elems
FROM (
  SELECT "nodeId", array_agg(VALUE ORDER BY position) AS elems
  FROM "default$default"."User_interestedFeatures"
  GROUP BY "nodeId"
) t
where t."nodeId" = "default$default"."User"."id";
DROP TABLE "default$default"."User_interestedFeatures";
```

If that helps :)

**Comment by Aldrian** [comment]
My original prisma type for reference:
`interestedFeatures: [String] @scalarList(strategy: RELATION)`

`I think this is just the SET NOT NULL causing the issue`

**Comment by matthewmueller** [comment]
Ah yes, good catch. I forgot about nullability. Can you double-check that it works without

```
ALTER TABLE "default$default"."User" ALTER COLUMN "interestedFeatures" SET NOT NULL;
```

?

**Comment by matthewmueller** [comment]
This SQL statement no longer shows up for nullable lists in `0.0.35`.
