### ISSUE TITLE
Wrap upgrade in a transaction

### ISSUE THREAD

**Issue by matthewmueller** [prisma/upgrade#29]
and add a big warning that you need to run `rollback` if you exit out for any reason.

perhaps attach to `process.on('exit')` to warn again

**Comment by janpio** [comment]
wait, is the tool executing SQL now?

**Comment by matthewmueller** [comment]
no, but we should instruct them to run `BEGIN;`, then `COMMIT;` or `ROLLBACK;`

**Comment by janpio** [comment]
Ah ok.

I copied the statements in blocks, so would probably miss he BEGIN or forget to run COMMIT.

(Not even sure if you can wrap DDL statements in a transaction in MySQL...)

**Comment by matthewmueller** [comment]
Closing for now, may re-open and investigate if folks run into problems.
