### ISSUE TITLE
Relation field after running Upgrade CLI is required but should be optional

### ISSUE THREAD

**Issue by nikolasburk** [prisma/upgrade#38]
This was my initial Prisma 1 datamodel:

```graphql
type User {
  id: ID! @id
  email: String @unique
  name: String!
  profile: Profile
  role: Role! @default(value: CUSTOMER)
  jsonData: Json 
}

type Profile {
  id: ID! @id
  bio: String
  user: User! @relation(link: INLINE)
}
```

I ran the Upgrade CLI and fixed all issues with the printed SQL statements. Then I re-introspected and finally ran the Upgrade CLI another time to add the remaining fixes to the Prisma schema.

The final output I got from the CLI was this:

```prisma
model User {
  email    String?   @unique
  id       String    @default(cuid()) @id
  jsonData Json?
  name     String
  role     User_role @default(CUSTOMER)
  Profile  Profile?
}

model Profile {
  bio  String?
  id   String  @default(cuid()) @id
  user String? @unique
  User User    @relation(fields: [user], references: [id])
}
```

The `Post` model currently throws an error because there's a mismatch with the relation field: The `user` foreign key field is optional, but the `User` relation field is required. This throws this error in the Prisma schema:

![image](https://user-images.githubusercontent.com/4058327/86580951-b1070300-bf7f-11ea-8291-624f1c8fbfc3.png)

It's a bit weird because it seems like the foreign key was already optional in the Prisma 1 database schema while it was required in the Prisma 1 datamodel (so probably a bug in Prisma 1?). Not quite sure how to handle this, we could either generate SQL statements to make the FK required as well so that introspection works correctly or accept that the upgrade will turn a required into an optional relation.

**Comment by matthewmueller** [comment]
Interesting. I'll add an SQL statement that makes the field non-optional, since that's the intent in DM1.

**Comment by matthewmueller** [comment]
Turns out MySQL is quite complicated, I've punted on that for now until someone requests it. See #56 for more details.
