### ISSUE TITLE
Cannot run prisma-upgrade with my schema

### ISSUE THREAD

**Issue by Aldrian** [prisma/upgrade#39]
Hi! When trying to upgrade my prisma 1.3x schema after introspecting, using prisma-upgrade, it fails immediately with this error: 

```
Error end of the stream or a document separator is expected at line 2, column 5:
      id: ID! @id
```

The generated introspect model
```
model Company {
  address        String?
  city           String?
  country        String?
  createdAt      DateTime
  id             String   @default(cuid()) @id
  identification String?
  name           String?
  postcode       String?
  size           String?
  updatedAt      DateTime
  vat            String?
  User           User[]   @relation("UserCompany", references: [id])
}

```

My prisma 1 type definition
```
type Company {
  id: ID! @id
  members: [User!]! @relation(name: "UserCompany")
  identification: String
  address: String
  city: String
  country: String @default(value: "FR")
  name: String
  size: String
  postcode: String
  vat: String
  createdAt: DateTime! @createdAt
  updatedAt: DateTime! @updatedAt
}
```

**Comment by matthewmueller** [comment]
Hi @Aldrian, 

what command are you using to run `prisma-upgrade`? What does your prisma.yml look like? (don't share secrets)

**Comment by Aldrian** [comment]
I'm using `npx prisma-upgrade deployment/prisma-orm/datamodel.prisma prisma/schema.prisma`

My prisma.yml: 

`endpoint: ${env:PRISMA_ENDPOINT}
datamodel: datamodel.graphql
secret: ${env:PRISMA_MANAGEMENT_API_SECRET}

generate:
  - generator: javascript-client
    output: ../../src/generated/prisma-client/pm2`

**Comment by Aldrian** [comment]
Oh wow, nice catch, sorry for that! I thought I was supposed to be running the existing schema across the generated schema
It works way better now 😅

**Comment by matthewmueller** [comment]
Great! Let me know if you run into anymore problems!
