### ISSUE TITLE
Breaking changes generated commands cannot be applied

### ISSUE THREAD

**Issue by Aldrian** [prisma/upgrade#41]
When trying to apply the SQL statements in order to fix the breaking changes on my prisma databases, the following commands cannot be applied

```
ALTER TABLE "default$default"."Media" ADD COLUMN "publisherId" character varying(25) NOT NULL;
ALTER TABLE "default$default"."Media" ADD CONSTRAINT "publisher" FOREIGN KEY ("publisherId") REFERENCES "default$default"."User"("id");
    UPDATE "default$default"."Media" SET "publisherId" = "default$default"."_UserMedias"."B" FROM "default$default"."_UserMedias" WHERE "default$default"."_UserMedias"."A" = "default$default"."Media"."id";
```

PGAdmin4 gives me the following error:

`ERROR:  column "publisherId" contains null values
SQL state: 23502`

**Comment by matthewmueller** [comment]
I think this is a duplicate of: https://github.com/prisma/upgrade/issues/36#issuecomment-654824417

Can you please give 0.0.25 a try? I just pushed it out about an hour ago.

**Comment by Aldrian** [comment]
having the same issue calling `npx prisma-upgrade@0.0.25 deployment/prisma-orm/prisma.yml prisma/schema.prisma --url http://localhost:4466`

Although the first lines shown are:

```
0 22

◮ Welcome to the interactive Prisma Upgrade CLI that helps with the
upgrade process from Prisma 1 to Prisma 2.
```

It seems that the version used by npx is still 0.0.22? Is there a way to force the upgrade to 0.0.25?

**Comment by matthewmueller** [comment]
Good catch! There was a stray `console.log`. I just pushed out `0.0.26`.

`npx prisma-upgrade --version` to check the version. 

If you're still running into this problem, please share the schema or a subset of the schema that illustrates this problem (e.g. Media & UserMedia models)

Also, do you have data in this database?

**Comment by Aldrian** [comment]
I am still running into this issue.

The first three commands printed by prisma-upgrade:

```
ALTER TABLE "default$default"."Media" ADD COLUMN "publisherId" character varying(25) NOT NULL;
    UPDATE "default$default"."Media" SET "publisherId" = "default$default"."_UserMedias"."A" FROM "default$default"."_UserMedias" WHERE "default$default"."_UserMedias"."B" = "default$default"."Media"."id";
    ALTER TABLE "default$default"."Media" ADD CONSTRAINT "publisher" FOREIGN KEY ("publisherId") REFERENCES "default$default"."User"("id");
    DROP TABLE "default$default"."_UserMedias";
```

The associated error:

```
ERROR:  column "publisherId" contains null values
SQL state: 23502
```

A subset of the prisma 1 media type:

type Media {
  id: ID! @id
  sourceUrl: String
  mimeType: String!
  size: Float!
  […]
  publisher: User! @relation(name: "UserMedias")
  […]
}

The related User type:

```
type User {
  id: ID! @id
  […]
  medias: [Media]! @relation(link: TABLE, name: "UserMedias", onDelete: CASCADE)
  […]
}
```

The introspected schema.prisma Media model:

```
model Media {
 […]
  id                    String             @id
 […]
  User                  User[]             @relation("UserMedias", references: [id])
}
```

And the User model:

```
model User {
 […]
  id                    String             @id
 […]
  Media                   Media[]                   @relation("UserMedias", references: [id])
  […]
}
```

**Comment by matthewmueller** [comment]
Thanks @Aldrian! I'll have a closer look and get back to you soon.

**Comment by Aldrian** [comment]
Thank you!

**Comment by matthewmueller** [comment]
Hi @Aldrian I think this is related to https://github.com/prisma/upgrade/issues/36#issuecomment-656090958

I just pushed up `0.0.27`, do you mind giving it a go on a test database?

**Comment by Aldrian** [comment]
Seems like it worked, thanks! 
I just had to remove some NOT NULL constraints `(ERROR:  column "XXXId" contains null values)`, it seems that I had a lot of orphans, which does not really concerns me since that base is more than 2 years old and have survived a few prisma 1 migrations. Hopefully all my data is still there 😅

On a side note, the link at the end of the prisma-upgrade wizard seems to be broken ([https://pris.ly/d/upgrading-the-prisma-layer](https://pris.ly/d/upgrading-the-prisma-layer)), I'll move on to the official doc!

**Comment by Aldrian** [comment]
Using prisma-studio, it seems that some relations, especially the ones between User and other models, like Media, are set to null now.

**Comment by Aldrian** [comment]
![Capture d’écran 2020-07-09 à 14 45 19](https://user-images.githubusercontent.com/5655615/87041742-f67f3680-c1f2-11ea-8cde-018232d02df8.png)
Here's the User model for example

**Comment by matthewmueller** [comment]
It sounds like the structure is okay now, but the data is not? If so, I'll need the following:

- A subset of the original data with field names (input)
- How that data should be linked (expected)
- How it is actually linked after the test (actual)

**Comment by Aldrian** [comment]
That's maybe why I had so many warnings telling me that my foreign keys had null elements in it. 

Do you have any template for the data you need? When you're talking about a subset of the original data, do you need the prisma 1 or 2 schema, or some actual datas?

**Comment by matthewmueller** [comment]
Actual (fake) data based on your application

**Comment by Aldrian** [comment]
I ran a simple query on my prisma 1 endpoint, taking the User and Media model as an example:

```
{
  user(where: { id: "cjwutc93401ip06672ur6do5t" }) {
    id
    firstName
    lastName
    medias {
      id
      title
      publisher {
        id
      }
    }
  }
}
```

Here's the result:

```
{
  "data": {
    "user": {
      "id": "cjwutc93401ip06672ur6do5t",
      "firstName": "Philippe",
      "lastName": "Demo",
      "medias": [
        {
          "id": "cjwvwyc5s04vh0667qlzqgg5n",
          "title": "Introduction to Web Accessibility and W3C Standards",
          "publisher": {
            "id": "cjwutc93401ip06672ur6do5t"
          }
        }
      ]
}

```

The prisma 1 schema subset associated with this request was pasted [above](https://github.com/prisma/upgrade/issues/41#issuecomment-654886347).

Here's a subset of the new introspected prisma 2 models after running prisma-upgrade

```
model User {
  firstName               String
  id                      String                    @default(cuid()) @id
  lastName                String
  Media                   Media[]
}
```

```
model Media {
  id                    String             @default(cuid()) @id
  publisherId           String?
  title                 String?
  User                  User?              @relation(fields: [publisherId], references: [id])
}
```

And the resulting data

![Capture d’écran 2020-07-09 à 15 45 21](https://user-images.githubusercontent.com/5655615/87047788-3a763980-c1fb-11ea-9c8e-2cef5fcd0e94.png)
![Capture d’écran 2020-07-09 à 15 43 46](https://user-images.githubusercontent.com/5655615/87047789-3ba76680-c1fb-11ea-91cf-27935dd0ee25.png)


I hope this is what you needed!

**Comment by matthewmueller** [comment]
Thanks for this @Aldrian. I'm working on replicating this exact issue in my tests so I can diagnose.

Do you have access to an SQL editor like TablePlus or Postico? For the example you provided:

```
{
  "data": {
    "user": {
      "id": "cjwutc93401ip06672ur6do5t",
      "firstName": "Philippe",
      "lastName": "Demo",
      "medias": [
        {
          "id": "cjwvwyc5s04vh0667qlzqgg5n",
          "title": "Introduction to Web Accessibility and W3C Standards",
          "publisher": {
            "id": "cjwutc93401ip06672ur6do5t"
          }
        }
      ]
}
```

There's a join table called `"postgres-media$dev"."_UserMedias"`. Could you share what's in the A and B column for this record? It should either be:

```
A: cjwutc93401ip06672ur6do5t
B: cjwvwyc5s04vh0667qlzqgg5n
```

or

```
A: cjwvwyc5s04vh0667qlzqgg5n
B: cjwutc93401ip06672ur6do5t
```

**Comment by Aldrian** [comment]
It is 

```
A: cjwvwyc5s04vh0667qlzqgg5n
B: cjwutc93401ip06672ur6do5t
```

However, after inspecting the cloned database where I applied the SQL statements generated by prisma-upgrade, I do not see any _UserMedias join table.
![Capture d’écran 2020-07-10 à 16 02 09](https://user-images.githubusercontent.com/5655615/87162819-bf7a5500-c2c6-11ea-8853-98d066407246.png)

**Comment by matthewmueller** [comment]
Thanks @Aldrian! I was able to reproduce your setup and see `error: column "publisherId" contains null values`.

That's all I need for now, I'll get back to you soon!

**Comment by Aldrian** [comment]
Thank you for the feedback!

**Comment by matthewmueller** [comment]
_Note to self (but sharing in case you're curious)_

```sql
-- 1. remove not null because we didn't set it yet
ALTER TABLE "postgres-media$dev"."Media" ADD COLUMN "publisherId" character varying(25);

-- 2. Reverse A and B again. This makes me think the fix I did the other day needs reworking
UPDATE "postgres-media$dev"."Media" SET "publisherId" = "postgres-media$dev"."_UserMedias"."B" FROM "postgres-media$dev"."_UserMedias" WHERE "postgres-media$dev"."_UserMedias"."A" = "postgres-media$dev"."Media"."id";

-- We've set the data, now set it back to NOT NULL
ALTER TABLE "postgres-media$dev"."Media" ALTER COLUMN "publisherId" set not null;

-- This now works as expected
ALTER TABLE "postgres-media$dev"."Media" ADD CONSTRAINT "publisher" FOREIGN KEY ("publisherId") REFERENCES "postgres-media$dev"."User"("id");

-- We can safely drop the JOIN table now.
DROP TABLE "postgres-media$dev"."_UserMedias";
```

**Comment by matthewmueller** [comment]
Hi @Aldrian. This issue should be fixed now in `0.0.28`.

**Comment by Aldrian** [comment]
Still having an issue for this set of commands:

```
ALTER TABLE "default$default"."WebTV" ADD COLUMN "publisherId" CHARACTER VARYING(25);
    UPDATE "default$default"."WebTV" SET "publisherId" = "default$default"."_UserWebTVs"."B" FROM "default$default"."_UserWebTVs" WHERE "default$default"."_UserWebTVs"."A" = "default$default"."WebTV"."id";
    ALTER TABLE "default$default"."WebTV" ALTER COLUMN "publisherId" set NOT NULL;
    ALTER TABLE "default$default"."WebTV" ADD CONSTRAINT "publisher" FOREIGN KEY ("publisherId") REFERENCES "default$default"."User"("id");
    DROP TABLE "default$default"."_UserWebTVs";
```

Same kind of relationship as the media => user relation : user has webtvs, webtv has an user

Could it just be an orphan, or is it still related to prisma upgrade?

**Comment by matthewmueller** [comment]
Can you do the same thing you did before? Share a (fake) linked row for the tables where it's failing?

- WebTV
- _UserWebTVs
- User

**Comment by Aldrian** [comment]
WEBTV
 
```
 {
    "id": "ck7boze7jvl4a0732fh3w2h7g",
 }

```
_UserWebTVs

```
  {
    "A": "cjwutc93401ip06672ur6do5t",
    "B": "ck7boze7jvl4a0732fh3w2h7g"
  }

```

User


```
 {
    "id": "cjwutc93401ip06672ur6do5t",
 }
```

**Comment by matthewmueller** [comment]
Perfect and I forgot to ask, can you share that portion of the Prisma 1 Schema?

**Comment by Aldrian** [comment]
```
type User {
  id: ID! @id
  webTVs: [WebTV!] @relation(link: TABLE, name: "UserWebTVs", onDelete: CASCADE)
}
```

```
type WebTV {
  id: ID! @id
  publisher: User! @relation(name: "UserWebTVs")
}
```

We'll get there! 😅

**Comment by Aldrian** [comment]
(If I may mention it, @janpio forked a version of my prisma 1 project when there was a call for production schemas, if that helps)

**Comment by matthewmueller** [comment]
Thanks @Aldrian really appreciate your patience. I think we're quite close. 

One last thing, are you seeing an error for this WebTV relation issue? Or just the data is missing?

**Comment by Aldrian** [comment]
Same error as before,  `ERROR: ERROR:  column "publisherId" contains null values`.
If I remove the NOT NULL statement, I guess I'll have the same behavior as before, the linked data will be missing

**Comment by matthewmueller** [comment]
Odd! Okay, I've got everything I need. Will get back soon. Thanks!

**Comment by matthewmueller** [comment]
Thanks again for the reproduction. I think I fixed this issue for good now. Please try `0.0.29` 😊

**Comment by Aldrian** [comment]
It worked! Except maybe on the non-breaking changes, it kept asking me to migrate my ids from varchar(25) to varchar(30).

All data and relations are here 😄 

Thanks a lot for your help! I'll keep migrating and see if other issues appear.

**Comment by matthewmueller** [comment]
Great to hear! That's expected because we're unable to differentiate between `varchar(25)` and `varchar(30)` without looking at your database directly. How do you suggest we improve that? 

> We can't determine if you've run this already. You do not need to run this twice.

Would a sentence like this helped?

**Comment by Aldrian** [comment]
If you're not able to know the difference, then sure, totally!
