### ISSUE TITLE
Update default value for converted Enum column 

### ISSUE THREAD

**Issue by sktt** [prisma/upgrade#60]
##### Running:
```
    ALTER TABLE "default$default"."User" ALTER COLUMN "status" SET DATA TYPE "default$default"."AccountStatus" using "status"::"default$default"."AccountStatus";
```

##### Results in:
```
ERROR:  default for column "status" cannot be cast automatically to type "default$default"."AccountStatus"
```

##### Because at a previous step we've been instructed to run:
```
    ALTER TABLE "default$default"."User" ALTER COLUMN "status" SET DEFAULT 'NORMAL';
```

##### Problem:
Either is prisma-upgrade is not aware of the default value for the enum being text, or the instructions are given in the wrong order.

##### Solution?
Before changing type...
- find its corresponding enum value
- remove default value, 
- alter the table column
- set new default to the enum value that corresponds the old text variant

**Comment by matthewmueller** [comment]
Do you mind sharing a subset of your Prisma 1 Schema that illustrates this problem? Then I can have a look.

**Comment by sktt** [comment]
Sure! 

```graphql
enum AccountStatus {
  NORMAL,
  BLOCKED
}

type User {
  ...
  status: AccountStatus! @default(value: NORMAL)
  ...
}
```
Let me know if you'd like to see something else of my configuration.

**Comment by matthewmueller** [comment]
Hmm. Unfortunately I'm not able to reproduce this. Given this schema:

```graphql
enum AccountStatus {
  NORMAL
  BLOCKED
}

type User {
  status: AccountStatus! @default(value: NORMAL)
}
```

I get instructed to run the following SQL:

```sql
CREATE TYPE "postgres-default-enum-1$dev"."AccountStatus" AS ENUM ('NORMAL', 'BLOCKED');
ALTER TABLE "postgres-default-enum-1$dev"."User" ALTER COLUMN "status" SET DATA TYPE "postgres-default-enum-1$dev"."AccountStatus" using "status"::"postgres-default-enum-1$dev"."AccountStatus";
ALTER TABLE "postgres-default-enum-1$dev"."User" ALTER COLUMN "status" SET DEFAULT 'NORMAL';
```

Resulting in:

```prisma
model User {
  id     String        @default(cuid()) @id
  status AccountStatus @default(NORMAL) @map("status")
}

enum AccountStatus {
  BLOCKED
  NORMAL
}
```

**Comment by sktt** [comment]
The order you've ALTER the table does not seem to be in the order that prisma-upgrade gives them in. Prisma-upgrade first instructs me to set new default: 

```sql
ALTER TABLE "default$default"."User" ALTER COLUMN "status" SET DEFAULT 'NORMAL';
```
the new default hence becomes `'NORMAL'::text`. Next running: 
```sql
ALTER TABLE "default$default"."User" ALTER COLUMN "status" SET DATA TYPE "default$default"."AccountStatus" using "status"::"default$default"."AccountStatus";
```
yields `ERROR:  default for column "status" cannot be cast automatically to type "default$default"."AccountStatus"`

I also don't see these `@map` directives, so I guess we're not issuing the same command. I am just using `npx prisma-upgrade --url ...  ./prisma.yml`

However, I've decided to not to this upgrade Enum and Json at all as it conflicts with prisma1, as pointed out in #61

**Comment by matthewmueller** [comment]
That's really weird, unless it's **another** command printing that beforehand. Are they together. 

Can you double-check the version you're running? It might have been something I fixed.

`npx prisma-upgrade --version`

**Comment by sktt** [comment]
prisma-upgrade is not a dependency so npx should just pull the latest one. 
```
npx prisma-upgrade --version                                                                                                                 
0.0.37
```

Ok, so I dropped the database and generate a new one with `prisma1 deploy`

Then `npx prisma-upgrade --url=http://localhost:4466 prisma.yml`

Actually! Now the DEFAULT updates are moved down! Great so this issue has been fixed.
