### ISSUE TITLE
Changing text to Enum or Json is a breaking change

### ISSUE THREAD

**Issue by sktt** [prisma/upgrade#61]
dialect: postgresql
These changes will indeed break prisma1 functionality. Maybe I don't get what is really meant by Breaking change? Is this a bug? I'm not sure.

**Comment by matthewmueller** [comment]
Hi @sktt,

You can read more about it here: https://www.prisma.io/docs/guides/upgrade-guides/upgrade-from-prisma-1/upgrading-the-prisma-layer-postgres#517-breaking-changes-detected

**Comment by sktt** [comment]
@matthewmueller I'm not convinced by this. It suggests that all points in 5.1 are *non-breaking* but updating text to Enum for prisma2 will create a conflict with INSERTS via prisma1. I think the same would go for Json.

**Comment by sktt** [comment]
indeed same goes for Json:
```
... {"exception":"org.postgresql.util.PSQLException: ERROR: column \"blah\" is of type jsonb but expression is of type character varying\n  Hint: You will need to rewrite or cast the expression. ...
```

**Comment by sktt** [comment]
Same goes for Enum as it tries to assign varying to column of type Enum.

```json
  "key": "error/unhandled",
  "requestId": "local:ckdx2d90r001k07515kgyddo1",
  "clientId": "default$default",
  "payload": {
    "exception": "org.postgresql.util.PSQLException: ERROR: column \"interval\" is of type \"default$default\".\"Interval\" but expression is of type character varying\n  Hint: You will need to rewrite or cast the expression.\n  Position: 415",
...
```
Are you sure this issue should remain closed, @matthewmueller ?

**Comment by matthewmueller** [comment]
Thanks @sktt. We're looking into this.

**Comment by divyenduz** [comment]
Thanks for reporting this @sktt 

These are indeed bugs, tracked here

Json: https://github.com/prisma/upgrade/issues/73
Enum: https://github.com/prisma/upgrade/issues/74

**Comment by sktt** [comment]
Okey! Closing this one then! 👍
