### ISSUE TITLE
Does not detect id column length.

### ISSUE THREAD

**Issue by sktt** [prisma/upgrade#62]
using postgres

Still asks me to run   Migrate IDs from varchar(25) to varchar(30) even after doing so and reintrospecting.

And the breaking change: __Fix one-to-many table relations__ includes queries with `varying(25)` types as well, which probably is supposed to be `varying(30)`.

Example:
```sql
--...
    ALTER TABLE "default$default"."User" ALTER COLUMN "id" SET DATA TYPE character varying(30);
--...
```
Followed by:
```sql
    ALTER TABLE "default$default"."Product" ADD COLUMN "sellerId" CHARACTER VARYING(25);
    UPDATE "default$default"."Product" SET "sellerId" = "default$default"."_ProductsSoldBy"."B" FROM "default$default"."_ProductsSoldBy" WHERE "default$default"."_ProductsSoldBy"."A" = "default$default"."Product"."id";
    ALTER TABLE "default$default"."Product" ALTER COLUMN "sellerId" set NOT NULL;
    -- Here, we reference a varying(25) to a varying(30).
    ALTER TABLE "default$default"."Product" ADD FOREIGN KEY ("sellerId") REFERENCES "default$default"."User"("id");
    DROP TABLE "default$default"."_ProductsSoldBy";
--...
```

The reintrospected schema.prisma file looks like so:
```graphql
model User {
  id                         String    @id
...
}
```

**Comment by matthewmueller** [comment]
You can ignore these commands if you've already run these commands.

Sorry about that, this is expected, but still very unclear. See: https://github.com/prisma/upgrade/issues/41#issuecomment-658254675

**Comment by sktt** [comment]
@matthewmueller 
Thank you for heads up on the first problem. The second concern is also that we're instructed to run
```sql
    ALTER TABLE "default$default"."Product" ADD COLUMN "sellerId" CHARACTER VARYING(25);
```

I assume here it should say `VARYING(30)` because the Id has been updated to `varying(30)`

**Comment by matthewmueller** [comment]
Yah, I noticed that the other day. I thinkkkk I should change that to 30, yep, but I need to test it. There might have been a reason for keeping it at 25. I'll create an issue.
