### ISSUE TITLE
No operator matches the given name

### ISSUE THREAD

**Issue by c316** [prisma/upgrade#79]
## Bug description

After starting the Prisma 1 to Prisma 2 migration locally I switched back to Prisma 1 and now I am getting many error messages. I didn't complete any of the "Breaking" changes section of the migration. 

Errors all look like this one.

```
ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)\\n java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)\\n java.lang.Thread.run(Thread.java:748)","message":"ERROR: operator does not exist: \"default$default\".\"CONTACT_CODE\" = character varying\n  Hint: No operator matches the given name and argument types. You might need to add explicit type casts.\n  Position: 121"}}
```

## How to reproduce

1. Setup a datamodel.prisma file with the enum and type below
```
enum CONTACT_CODE {
  JB
  UJ
  GB
  UG
  UNKNOWN
}
type Contact {
  id: ID! @id
  code: CONTACT_CODE
}
```
2. Attempt the migration using the docs
3. Now comment out the .env variables and run using Prisma 1. 

I think something has been done to the database and now I can't retrieve contacts that need the, "CONTACT_CODE"

## Environment & setup

- OS:  Mac OS
- Database:  PostgreSQL

**Comment by janpio** [comment]
Thanks, I moved this issue to the `prisma-upgrade` tool as this was most probably caused by the queries you executed after it told you so.

**Comment by matthewmueller** [comment]
@c316 just to clarify, did you run the `prisma-upgrade` too?

**Comment by c316** [comment]
> @c316 just to clarify, did you run the `prisma-upgrade` tool? e.g. `npx prisma-upgrade prisma.yml prisma.schema`

Yes

**Comment by matthewmueller** [comment]
Got it, thanks for the fast reply!

We just fixed the prisma-upgrade tool a 4 days back to turn enums into a breaking change for Postgres. That might be the problem: https://github.com/prisma/upgrade/blob/master/History.md#0038--2020-08-21

Please make sure you're running `0.0.40`. You can check with `prisma-upgrade -v`

**Comment by c316** [comment]
@matthewmueller Yes, that probably is it. Do you happen to know how I can fix my database now? Thank you

**Comment by matthewmueller** [comment]
Assuming, this is a non-production issue, the recommended approach would be to restore from a backup.

If you can't do that, I think you'll just need to convert those enum columns back to `TEXT`. 

The generated command to change it to enum looks like this: https://github.com/prisma/upgrade/blob/0a97aa671815fa87da7ebaa53bbae26f09560db7/src/sql/index.ts#L235
