### ISSUE TITLE
UPPERCASE generated MySQL

### ISSUE THREAD

**Issue by janpio** [prisma/upgrade#9]
MySQL users expect `ALTER TABLE` instead of `alter table`.

**Comment by matthewmueller** [comment]
not a huge fan of this since aesthetically since it's like we're yelling at them, but curious what other people think.

**Comment by janpio** [comment]
As a MySQL user you are used to that as it is how it is always formatted: https://dev.mysql.com/doc/refman/8.0/en/alter-table.html

**Comment by nikolasburk** [comment]
I'm also in favor of uppercasing _all_ SQL keywords/commands, that's also the convention we're following in the docs and other content resources at the moment.

**Comment by matthewmueller** [comment]
Fixed in latest
