### ISSUE TITLE
Broken documentation links

### ISSUE THREAD

**Issue by baptistemarchand** [prisma/upgrade#91]
When running `npx prisma-upgrade` I get the following broken links:

https://pris.ly/d/schema-incompatibilities
https://pris.ly/d/schema-incompatibilities#default-values-arent-represented-in-database
https://pris.ly/d/schema-incompatibilities#inline-1-1-relations-are-recognized-as-1-n-missing-unique-constraint
https://pris.ly/d/schema-incompatibilities#mismatching-cuid-length

**Comment by mhwelander** [comment]
Now fixed - thank you! 💚
